/*

       This file is part of the PDP software package.
		 
       Copyright 1987 by James L. McClelland and David E. Rumelhart.
       
       Please refer to licensing information in the file license.txt,
       which is in the same directory with this source file and is
       included here by reference.
*/


/* file: iac.h

	Definitions for the iac program.
    
        First version implemented by JLM
	
	Date of last revision:  8-12-87/JLM.
*/
